version: "3"
services:
  jr_server:
    image: jira_app
    container_name: jira_app
    depends_on:
      - postgres-db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      db_url: jdbc:postgresql://postgres-db:5432/jira
      db_login: jira
      db_password: JiraRush
      github_id: 3d0d8738e65881fff266
      github_secret: 0f97031ce6178b7dfb67a6af587f37e222a16120
      google_id: 329113642700-f8if6pu68j2repq3ef6umd5jgiliup60.apps.googleusercontent.com
      google_secret: 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
      gitlab_id: b8520a3266089063c0d8261cce36971defa513f5ffd9f9b7a3d16728fc83a494
      gitlab_secret: e72c65320cf9d6495984a37b0f9cc03ec46be0bb6f071feaebbfe75168117004
      mail_username: jira4jr@gmail.com
      mail_password: zdfzsrqvgimldzyj
    networks:
      - jr_network

  postgres-db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: jira
      POSTGRES_PASSWORD: JiraRush
      POSTGRES_DB: jira
    volumes:
      - pg-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - jr_network


  nginx:
    container_name: jira_nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./resources:/opt/jirarush/resources
    networks:
      - jr_network

networks:
  jr_network:
    driver: bridge

volumes:
  pg-data:
